### ISSUE TITLE
frost-text: README lists an align setting of "center" but no corresponding class exists

### ISSUE THREAD

**Issue by juwara0** [juwara0/ember-frost-core#13]
Should the align setting of "center" be removed from the README API for frost-text or should a "center" class be added like exists for "right": https://github.com/juwara0/ember-frost-core/blob/64e9293ce4381ece9195a5a1bf0b6089434ce952/addon/styles/_frost-text.scss#L44

**Comment by Jasonjys** [comment]
The align setting of "center" should be removed.
