### ISSUE TITLE
frost-textarea: Clear functionality is not working in the demo app

### ISSUE THREAD

**Issue by Jasonjys** [juwara0/ember-frost-core#14]
It works in the integration test but there is nothing I can click in the demo app.
https://github.com/juwara0/ember-frost-core/blob/64e9293ce4381ece9195a5a1bf0b6089434ce952/addon/templates/components/frost-textarea.hbs#L17

**Comment by juwara0** [comment]
Closed via: https://github.com/juwara0/ember-frost-core/pull/19
